[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
simple = "DEFuzL6ArEcszLSgy1pQBLSdyBd7BKR5CUdckq2RXn2A"
solana_vuln_game = "4busdpFhfoenYZbhmtj6YHYyKq9cvoGqBUTimp5URdeW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./walletSec.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
